services:
  api: # Note: any changes require a rebuild and restart
    build: ./api
    networks:
      - app_network
    container_name: api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy  # Tells API to wait until DB is actually ready

  db:
    image: mysql:8.0
    networks:
      - app_network
    container_name: db
    restart: always
    command: # Custom MySQL configuration for better performance with large datasets
      - "--innodb_buffer_pool_size=1G"
      - "--innodb_log_file_size=256M"
      - "--max_allowed_packet=256M"
      - "--innodb_redo_log_capacity=512M"
    ports:
      - "127.0.0.1:3307:3306" # Restricts access to local machine
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=course_management 
    volumes:
      - db_data:/var/lib/mysql # Persists data across container restarts
      - ./database:/docker-entrypoint-initdb.d # Initialize db with SQL files
    healthcheck: # Makes sure API wait until the databse is up and running 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:

networks:
  app_network:
    name: campus_backend_link
    driver: bridge
