-- Insert courses
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organizational Behavior Practicum', 'ORGA5090');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Machine Learning', 'MACH1249');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Public Health 136', 'PUBL4074');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cognitive Science Workshop', 'COGN4425');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology 189', 'SOCI5691');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Public Health Seminar', 'PUBL5622');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Environmental Science Lab', 'ENVI8822');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Data Structures', 'DATA8774');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Literature II', 'LITE6348');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Differential Equations I', 'DIFF6654');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anthropology Workshop', 'ANTH3188');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anatomy 596', 'ANAT1837');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Probability', 'PROB5113');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human-Computer Interaction Workshop', 'HUMA7290');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Artificial Intelligence I', 'ARTI7430');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Oceanography', 'OCEA9106');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Creative Writing', 'CREA6520');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Psychology', 'PSYC3894');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human Resource Management II', 'HUMA4672');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Corporate Finance', 'CORP3814');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology I', 'SOCI4463');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Software Engineering', 'SOFT7896');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Kinesiology 170', 'KINE2235');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Networks 478', 'COMP4884');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Science Seminar', 'COMP1371');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Political Science Workshop', 'POLI7811');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Genetics Independent Study', 'GENE9967');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Earth Science Seminar', 'EART7332');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Computer Science', 'COMP6077');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Physiology 556', 'PHYS9136');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Molecular Biology IV', 'MOLE3235');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anatomy Workshop', 'ANAT7992');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Kinesiology Independent Study', 'KINE8345');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography Seminar', 'OCEA8786');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Macroeconomics Independent Study', 'MACR1956');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Human Resource Management', 'HUMA9701');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Genetics 423', 'GENE5532');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Astrophysics 530', 'ASTR7588');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Artificial Intelligence IV', 'ARTI7536');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience 369', 'NEUR1435');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Political Science', 'POLI7620');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology Seminar', 'SOCI7296');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organic Chemistry IV', 'ORGA2178');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Discrete Mathematics Lab', 'DISC7654');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Literature 578', 'LITE4169');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Genetics 416', 'GENE3685');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ethics 169', 'ETHI4353');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anthropology 198', 'ANTH6066');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Oceanography', 'OCEA6979');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Molecular Biology I', 'MOLE7706');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Financial Accounting 317', 'FINA7112');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ethics 456', 'ETHI2935');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Macroeconomics IV', 'MACR2049');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations Seminar', 'INTE5887');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Literature 505', 'LITE1941');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Genetics', 'GENE2921');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Kinesiology 322', 'KINE2795');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Marketing Management III', 'MARK7874');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Nutrition', 'NUTR2492');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human-Computer Interaction IV', 'HUMA8654');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ecology 575', 'ECOL6961');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Literature', 'LITE5188');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anthropology Seminar', 'ANTH7919');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Linear Algebra', 'LINE9710');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Data Structures', 'DATA7852');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Earth Science 506', 'EART4468');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations Practicum', 'INTE6615');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Entrepreneurship', 'ENTR7067');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in World History', 'WORL6510');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography Independent Study', 'OCEA3463');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ecology Practicum', 'ECOL5999');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linguistics 523', 'LING6734');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Political Science', 'POLI4495');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Molecular Biology 404', 'MOLE3871');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Astrophysics Practicum', 'ASTR7240');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography 185', 'OCEA7963');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ecology Independent Study', 'ECOL6031');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Operating Systems', 'OPER4407');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Science III', 'COMP5887');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Macroeconomics 258', 'MACR1580');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern International Relations', 'INTE6369');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Kinesiology', 'KINE7450');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Law 348', 'BUSI3975');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Music Theory 100', 'MUSI1299');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Entrepreneurship 298', 'ENTR8402');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Anthropology', 'ANTH5593');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Kinesiology', 'KINE4332');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Operating Systems 270', 'OPER7241');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Algorithm Analysis', 'ALGO4587');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Information Systems', 'INFO3841');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Thermodynamics', 'THER8491');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of World History', 'WORL2636');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Cloud Computing', 'CLOU8915');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Financial Accounting 247', 'FINA2301');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Thermodynamics Workshop', 'THER3700');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Linear Algebra', 'LINE5624');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Discrete Mathematics', 'DISC6828');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Political Science 500', 'POLI7774');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Marketing Management Lab', 'MARK9553');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cryptography 149', 'CRYP3812');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Machine Learning 271', 'MACH2965');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Algorithm Analysis 209', 'ALGO2666');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linguistics IV', 'LING9558');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Artificial Intelligence Seminar', 'ARTI9846');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Discrete Mathematics', 'DISC1423');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Creative Writing 458', 'CREA9726');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Quantum Mechanics 393', 'QUAN2314');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Entrepreneurship', 'ENTR5403');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Organic Chemistry', 'ORGA7366');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Music Theory', 'MUSI9051');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Microeconomics III', 'MICR3098');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Genetics Seminar', 'GENE8967');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience 357', 'NEUR6481');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Music Theory 277', 'MUSI3648');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Nutrition', 'NUTR2416');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Molecular Biology 319', 'MOLE2410');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Entrepreneurship Practicum', 'ENTR2120');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cryptography III', 'CRYP4438');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Operating Systems', 'OPER7366');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Artificial Intelligence III', 'ARTI8482');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Business Ethics', 'BUSI9434');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('World History Independent Study', 'WORL4417');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Software Engineering 198', 'SOFT6929');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ecology II', 'ECOL4691');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of International Relations', 'INTE1810');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Genetics IV', 'GENE4330');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Calculus', 'CALC1461');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Machine Learning 308', 'MACH3900');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Linear Algebra', 'LINE2410');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Psychology Workshop', 'PSYC7503');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Nutrition', 'NUTR4533');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Neuroscience', 'NEUR4824');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Political Science Practicum', 'POLI4234');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity IV', 'CYBE4637');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Algorithm Analysis I', 'ALGO5927');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Information Systems 237', 'INFO5554');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Nutrition', 'NUTR7098');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience 347', 'NEUR5049');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Data Structures 483', 'DATA9436');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Macroeconomics', 'MACR2889');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Macroeconomics', 'MACR2862');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cryptography Seminar', 'CRYP8172');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Kinesiology 245', 'KINE1085');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('World History Lab', 'WORL7602');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Anthropology', 'ANTH4483');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Networks 290', 'COMP6771');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Environmental Science Practicum', 'ENVI5542');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Linguistics', 'LING3544');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Database Systems', 'DATA6140');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Art History', 'ARTH8278');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Music Theory Lab', 'MUSI6693');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Probability 258', 'PROB3968');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Machine Learning Workshop', 'MACH3395');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Art History', 'ARTH9085');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Anatomy', 'ANAT9585');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Literature III', 'LITE8576');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Software Engineering 460', 'SOFT9026');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Ethics', 'ETHI7892');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Nutrition 444', 'NUTR9031');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Music Theory', 'MUSI6592');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Financial Accounting', 'FINA4772');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology Independent Study', 'SOCI9717');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Business Ethics', 'BUSI7992');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Corporate Finance 329', 'CORP4132');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Anthropology', 'ANTH8925');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Physiology', 'PHYS7264');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ecology 281', 'ECOL7026');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Web Development 202', 'WEBD7198');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Astrophysics', 'ASTR6090');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Nutrition', 'NUTR7745');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Networks II', 'COMP1979');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Software Engineering Seminar', 'SOFT1248');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Information Systems II', 'INFO4672');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Macroeconomics', 'MACR4507');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Creative Writing Workshop', 'CREA9950');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Earth Science', 'EART2025');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cloud Computing 169', 'CLOU7640');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Machine Learning III', 'MACH6400');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Networks Workshop', 'COMP1783');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cognitive Science II', 'COGN6300');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Algorithm Analysis', 'ALGO8017');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Robotics 504', 'ROBO5923');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Literature', 'LITE8355');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Science IV', 'COMP6424');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Cybersecurity', 'CYBE7630');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography 493', 'OCEA8199');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Corporate Finance 392', 'CORP6549');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity 228', 'CYBE9179');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Microeconomics 313', 'MICR8714');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Database Systems', 'DATA5231');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Literature 358', 'LITE1330');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Sociology', 'SOCI2561');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology Lab', 'SOCI8494');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity 132', 'CYBE8409');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography 325', 'OCEA5656');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Differential Equations', 'DIFF7253');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Political Science', 'POLI2692');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Financial Accounting Workshop', 'FINA4790');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Probability 400', 'PROB9509');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Nutrition Workshop', 'NUTR6736');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Art History', 'ARTH6287');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Statistics I', 'STAT3506');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience 367', 'NEUR9204');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Software Engineering Practicum', 'SOFT9113');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of European History', 'EURO2724');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Financial Accounting', 'FINA1601');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anthropology Practicum', 'ANTH5643');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cognitive Science 133', 'COGN3278');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Entrepreneurship', 'ENTR7018');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Microeconomics I', 'MICR3789');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Earth Science Practicum', 'EART9956');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Political Science', 'POLI1840');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Astrophysics', 'ASTR1616');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Anthropology', 'ANTH7239');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Discrete Mathematics', 'DISC2119');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Software Engineering', 'SOFT7151');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Molecular Biology 548', 'MOLE1589');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Kinesiology', 'KINE9844');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Thermodynamics Lab', 'THER4878');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Art History II', 'ARTH2053');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity 479', 'CYBE7491');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Data Structures', 'DATA4870');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Operating Systems', 'OPER4508');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Calculus', 'CALC2331');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Operating Systems', 'OPER4877');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Calculus II', 'CALC6845');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Database Systems I', 'DATA5006');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Environmental Science IV', 'ENVI8544');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Artificial Intelligence', 'ARTI8840');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Algorithm Analysis III', 'ALGO4430');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Music Theory', 'MUSI4707');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Thermodynamics', 'THER5636');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations Lab', 'INTE8509');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Information Systems III', 'INFO8480');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Physiology', 'PHYS5984');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Macroeconomics 475', 'MACR6484');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cognitive Science 403', 'COGN1717');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organic Chemistry I', 'ORGA9945');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Neuroscience', 'NEUR5688');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Machine Learning II', 'MACH6388');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Data Structures', 'DATA2451');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Art History IV', 'ARTH5073');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Music Theory IV', 'MUSI3626');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Organizational Behavior', 'ORGA5309');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Machine Learning', 'MACH9645');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Oceanography', 'OCEA4408');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Human-Computer Interaction', 'HUMA9332');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Cloud Computing', 'CLOU2066');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Marketing Management 447', 'MARK3821');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Ethics', 'ETHI9411');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Astrophysics', 'ASTR4745');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Entrepreneurship', 'ENTR5967');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity 103', 'CYBE2278');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Entrepreneurship Lab', 'ENTR4479');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ethics I', 'ETHI8199');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Environmental Science 430', 'ENVI7164');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Operating Systems', 'OPER1842');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Literature 162', 'LITE7326');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity III', 'CYBE9601');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human Resource Management 201', 'HUMA4988');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organic Chemistry III', 'ORGA3142');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Quantum Mechanics 278', 'QUAN7459');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cryptography 124', 'CRYP8518');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cognitive Science 371', 'COGN6627');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linear Algebra 464', 'LINE2014');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Software Engineering Lab', 'SOFT7627');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organic Chemistry 590', 'ORGA9558');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Human Resource Management', 'HUMA3939');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linear Algebra IV', 'LINE7850');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience Practicum', 'NEUR6146');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Computer Science', 'COMP4203');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Law 572', 'BUSI4827');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Supply Chain Management 518', 'SUPP3876');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Linguistics', 'LING4803');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Software Engineering', 'SOFT9574');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anatomy 255', 'ANAT4517');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cryptography IV', 'CRYP1792');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Computer Networks', 'COMP2505');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Entrepreneurship Workshop', 'ENTR6017');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Microeconomics 487', 'MICR8891');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Machine Learning', 'MACH3471');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Calculus 183', 'CALC3765');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary International Relations', 'INTE5907');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Software Engineering III', 'SOFT8837');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Business Law', 'BUSI9014');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('World History 583', 'WORL8026');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Cloud Computing', 'CLOU9100');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Molecular Biology', 'MOLE8445');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ethics Practicum', 'ETHI7332');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Physiology', 'PHYS3538');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Calculus', 'CALC9820');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology 192', 'SOCI4460');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Environmental Science 142', 'ENVI5995');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Oceanography', 'OCEA8860');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linguistics Practicum', 'LING3431');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations 296', 'INTE2847');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations 295', 'INTE6240');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linear Algebra I', 'LINE4318');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Business Law', 'BUSI3209');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('European History Lab', 'EURO2067');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Calculus Independent Study', 'CALC5164');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Science 162', 'COMP1931');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Oceanography', 'OCEA6623');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Philosophy Workshop', 'PHIL8702');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linguistics 207', 'LING9963');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Environmental Science', 'ENVI7384');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Database Systems Lab', 'DATA3366');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human-Computer Interaction 551', 'HUMA5619');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Cloud Computing', 'CLOU4957');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Philosophy', 'PHIL9807');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Networks IV', 'COMP5781');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations 528', 'INTE6683');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Cybersecurity', 'CYBE2744');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Artificial Intelligence Independent Study', 'ARTI5924');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Political Science', 'POLI6868');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Sociology', 'SOCI8083');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Robotics', 'ROBO3372');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Networks 447', 'COMP8535');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anatomy 593', 'ANAT3154');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Earth Science 117', 'EART5082');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Art History 383', 'ARTH5411');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Science Workshop', 'COMP3296');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Ecology', 'ECOL4234');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Statistics', 'STAT7695');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Cryptography', 'CRYP7453');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of European History', 'EURO4089');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Neuroscience', 'NEUR7683');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity Independent Study', 'CYBE3933');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Operating Systems', 'OPER4471');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations 109', 'INTE7596');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Linear Algebra 180', 'LINE9989');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Human Resource Management', 'HUMA9088');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Entrepreneurship', 'ENTR1915');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Ethics 536', 'BUSI3552');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organizational Behavior II', 'ORGA6909');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Supply Chain Management 363', 'SUPP3032');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Music Theory', 'MUSI3177');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography Practicum', 'OCEA1494');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Nutrition 125', 'NUTR1789');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Astrophysics', 'ASTR8487');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Macroeconomics', 'MACR9778');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity Practicum', 'CYBE1497');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Molecular Biology', 'MOLE3565');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Quantum Mechanics 167', 'QUAN9251');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Human Resource Management', 'HUMA8140');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ethics 179', 'ETHI6948');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Business Law', 'BUSI6867');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organizational Behavior III', 'ORGA1791');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations Workshop', 'INTE2050');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Microeconomics IV', 'MICR1721');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Statistics', 'STAT4318');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Database Systems 592', 'DATA8380');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Macroeconomics 494', 'MACR4124');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Entrepreneurship II', 'ENTR7614');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Calculus Lab', 'CALC5156');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Ethics 182', 'BUSI3415');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Kinesiology Practicum', 'KINE5078');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Public Health', 'PUBL2262');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Web Development', 'WEBD8675');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Molecular Biology', 'MOLE2245');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Law I', 'BUSI3493');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Artificial Intelligence', 'ARTI3440');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Astrophysics', 'ASTR9749');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations 279', 'INTE1038');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Nutrition III', 'NUTR8195');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Law IV', 'BUSI7660');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Database Systems 141', 'DATA3955');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('European History Independent Study', 'EURO1815');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Quantum Mechanics 535', 'QUAN9089');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Corporate Finance', 'CORP1456');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cognitive Science IV', 'COGN8784');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Thermodynamics', 'THER2012');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Financial Accounting', 'FINA9518');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience 507', 'NEUR6510');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Web Development', 'WEBD4229');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Networks 455', 'COMP3910');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Creative Writing 568', 'CREA7622');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Quantum Mechanics', 'QUAN4328');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Seminar in Oceanography', 'OCEA4348');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Genetics 354', 'GENE5894');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Creative Writing III', 'CREA9755');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Linguistics', 'LING6842');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Sociology', 'SOCI5194');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Supply Chain Management', 'SUPP8082');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Modern Microeconomics', 'MICR6636');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('World History 328', 'WORL8777');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology II', 'SOCI4138');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Web Development III', 'WEBD5664');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Financial Accounting Practicum', 'FINA5233');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Law Workshop', 'BUSI7258');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Web Development Practicum', 'WEBD5799');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Thermodynamics IV', 'THER1291');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Data Structures 297', 'DATA3178');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Database Systems Practicum', 'DATA1215');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('World History 123', 'WORL5169');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience 164', 'NEUR2692');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Thermodynamics 289', 'THER6772');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Quantum Mechanics 459', 'QUAN6350');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Macroeconomics 380', 'MACR9024');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Sociology 309', 'SOCI8408');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Computer Science', 'COMP2028');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human-Computer Interaction 164', 'HUMA3027');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anthropology 482', 'ANTH4765');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Advanced Literature', 'LITE4569');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography 572', 'OCEA8514');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Marketing Management', 'MARK4830');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Cybersecurity', 'CYBE4394');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Literature 385', 'LITE1069');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Psychology', 'PSYC9068');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Algorithm Analysis 186', 'ALGO5494');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience IV', 'NEUR7386');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Political Science III', 'POLI8335');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Computer Networks', 'COMP2802');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Principles of Organic Chemistry', 'ORGA5774');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Ecology', 'ECOL4732');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Environmental Science 419', 'ENVI6506');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Financial Accounting 232', 'FINA2727');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Ecology', 'ECOL1931');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Microeconomics Workshop', 'MICR7126');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organizational Behavior 470', 'ORGA8023');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Information Systems', 'INFO7524');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Molecular Biology 140', 'MOLE9977');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Computer Science Independent Study', 'COMP3848');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('European History II', 'EURO2332');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Political Science 210', 'POLI3925');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Nutrition Seminar', 'NUTR6507');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Oceanography 316', 'OCEA5529');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human-Computer Interaction 301', 'HUMA3749');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Macroeconomics Seminar', 'MACR5796');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Robotics II', 'ROBO8084');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Astrophysics III', 'ASTR1876');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Artificial Intelligence', 'ARTI1847');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human-Computer Interaction Independent Study', 'HUMA9349');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cloud Computing I', 'CLOU1596');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Computer Science', 'COMP3303');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Operating Systems 487', 'OPER1128');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Corporate Finance 542', 'CORP8042');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Ethics', 'ETHI8612');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('European History Seminar', 'EURO7648');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Psychology 221', 'PSYC8027');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Earth Science IV', 'EART5377');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cloud Computing 207', 'CLOU2902');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity Workshop', 'CYBE7976');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Environmental Science', 'ENVI2213');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Astrophysics', 'ASTR2517');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Contemporary Philosophy', 'PHIL7236');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Neuroscience I', 'NEUR4861');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('European History I', 'EURO7840');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Data Structures II', 'DATA7817');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Business Law', 'BUSI9586');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('World History 113', 'WORL9408');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Public Health', 'PUBL5586');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Psychology 393', 'PSYC5854');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Operating Systems', 'OPER7354');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Marketing Management 262', 'MARK4633');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Anthropology 276', 'ANTH2797');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Anthropology', 'ANTH9294');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Music Theory I', 'MUSI3796');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Cybersecurity', 'CYBE9773');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human-Computer Interaction Lab', 'HUMA4153');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Computer Science', 'COMP7762');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Operating Systems Lab', 'OPER8842');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Ethics IV', 'BUSI4457');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Topics in Linear Algebra', 'LINE9131');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Calculus 229', 'CALC7045');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Artificial Intelligence 456', 'ARTI5062');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Database Systems III', 'DATA8366');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organizational Behavior Independent Study', 'ORGA9168');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Anatomy', 'ANAT2947');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Supply Chain Management 597', 'SUPP7420');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Corporate Finance II', 'CORP2614');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Fundamentals of Microeconomics', 'MICR3196');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Statistics Practicum', 'STAT8316');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Kinesiology Seminar', 'KINE8748');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Microeconomics 204', 'MICR3923');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Organizational Behavior I', 'ORGA8338');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Theoretical Data Structures', 'DATA1527');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Astrophysics II', 'ASTR9041');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Supply Chain Management 535', 'SUPP8424');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Foundations of Thermodynamics', 'THER7478');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Human Resource Management Workshop', 'HUMA8241');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Genetics I', 'GENE3274');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Introduction to Organizational Behavior', 'ORGA7109');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Issues in Corporate Finance', 'CORP8253');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Research Methods in Differential Equations', 'DIFF5538');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Business Law Seminar', 'BUSI6808');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Differential Equations 129', 'DIFF6776');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Applied Information Systems', 'INFO1381');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Algorithm Analysis Workshop', 'ALGO1516');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Cybersecurity Seminar', 'CYBE8027');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Astrophysics 532', 'ASTR4556');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Philosophy III', 'PHIL1855');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('International Relations 282', 'INTE8088');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Experimental Algorithm Analysis', 'ALGO6395');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Music Theory III', 'MUSI6651');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Survey of Astrophysics', 'ASTR2929');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Ecology 272', 'ECOL8551');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Corporate Finance', 'CORP1083');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Operating Systems Workshop', 'OPER8041');
INSERT IGNORE INTO courses (course_name, course_code) VALUES ('Perspectives on Organizational Behavior', 'ORGA5575');
