SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
SET AUTOCOMMIT = 0;

INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Anthropology', 'ANTH3089');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Database Systems Lab', 'DATA4780');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anatomy Seminar', 'ANAT5342');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Calculus Workshop', 'CALC7051');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Psychology', 'PSYC7263');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Linguistics', 'LING2921');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Database Systems IV', 'DATA4609');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Human-Computer Interaction', 'HUMA9116');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Nursing Practice I', 'NURS5047');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology 518', 'PHYS8171');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human Resource Management I', 'HUMA3902');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology Seminar', 'TOXI8608');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Linguistics', 'LING5414');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Biomechanics II', 'BIOM4412');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anthropology 543', 'ANTH2615');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning 491', 'MACH5579');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Psychology', 'PSYC6333');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Bioethics Practicum', 'BIOE6514');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Oceanography III', 'OCEA1348');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Discrete Mathematics IV', 'DISC8033');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Gerontology 313', 'GERO2528');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning 245', 'MACH7105');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Nutrition', 'NUTR6564');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in International Relations', 'INTE9822');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Entrepreneurship 492', 'ENTR9039');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Artificial Intelligence 201', 'ARTI1333');
INSERT IGNORE INTO courses (name, course_code) VALUES ('World History 246', 'WORL8052');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Public Health', 'PUBL7939');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Financial Accounting', 'FINA3607');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology II', 'TOXI2786');
INSERT IGNORE INTO courses (name, course_code) VALUES ('European History Workshop', 'EURO6780');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology Workshop', 'PHYS8754');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linear Algebra 229', 'LINE3808');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Earth Science 510', 'EART5935');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Quantum Mechanics 566', 'QUAN3870');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Discrete Mathematics 562', 'DISC1425');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Oceanography Seminar', 'OCEA2156');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Medical Imaging 236', 'MEDI8176');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Thermodynamics 333', 'THER8301');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Earth Science Practicum', 'EART5414');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Sociology', 'SOCI1838');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Artificial Intelligence 400', 'ARTI3259');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Algorithm Analysis II', 'ALGO4907');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Biomechanics 512', 'BIOM5507');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance Seminar', 'CORP7012');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Artificial Intelligence Seminar', 'ARTI4672');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Genetics II', 'GENE1321');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Artificial Intelligence 521', 'ARTI4195');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Ethics Independent Study', 'BUSI9150');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physical Therapy I', 'PHYS8659');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance 534', 'CORP5351');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Applied Business Law', 'BUSI5873');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Corporate Finance', 'CORP7071');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ecology II', 'ECOL8214');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Pathology', 'PATH7583');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Supply Chain Management III', 'SUPP1592');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organizational Behavior Practicum', 'ORGA3189');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology 263', 'TOXI3124');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Sociology 106', 'SOCI6850');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cloud Computing 331', 'CLOU9182');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Discrete Mathematics II', 'DISC8822');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Sociology III', 'SOCI6823');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Web Development Independent Study', 'WEBD1909');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Applied Anthropology', 'ANTH5810');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Microeconomics I', 'MICR9675');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Microeconomics Workshop', 'MICR8643');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Creative Writing III', 'CREA8120');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Thermodynamics 131', 'THER1904');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Law IV', 'BUSI2320');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning 107', 'MACH1688');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance 321', 'CORP2476');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Anthropology', 'ANTH6629');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Music Theory Seminar', 'MUSI9262');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Kinesiology 347', 'KINE4851');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Ecology', 'ECOL9283');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human-Computer Interaction 534', 'HUMA9455');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Discrete Mathematics', 'DISC5231');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Networks 580', 'COMP5862');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Financial Accounting 178', 'FINA9695');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology 211', 'EPID8175');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Nutrition', 'NUTR5450');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Gerontology 178', 'GERO4536');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Software Engineering Workshop', 'SOFT4015');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Creative Writing 154', 'CREA4273');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pharmacology 395', 'PHAR4722');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Anthropology', 'ANTH1901');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Ecology', 'ECOL8235');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Calculus 358', 'CALC6756');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Philosophy Lab', 'PHIL5015');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Thermodynamics 256', 'THER2832');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Financial Accounting 252', 'FINA9680');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Entrepreneurship Workshop', 'ENTR6651');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Marketing Management Lab', 'MARK9176');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Physical Therapy', 'PHYS8840');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Modern Public Health', 'PUBL4716');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cryptography Independent Study', 'CRYP6795');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Macroeconomics', 'MACR2571');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Music Theory 278', 'MUSI9370');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anatomy 599', 'ANAT8671');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linguistics 151', 'LING8385');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Law Seminar', 'BUSI8059');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Physical Therapy', 'PHYS6717');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Web Development I', 'WEBD3668');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Human-Computer Interaction', 'HUMA3013');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Sociology', 'SOCI6984');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Organizational Behavior', 'ORGA4543');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Robotics', 'ROBO6798');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Science 562', 'COMP4564');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Ethics 335', 'BUSI4972');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Psychology I', 'PSYC2597');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology Practicum', 'TOXI8940');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human-Computer Interaction Independent Study', 'HUMA9091');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning Practicum', 'MACH1014');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Gerontology Lab', 'GERO5453');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pharmacology 379', 'PHAR7006');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pharmacology Practicum', 'PHAR1422');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Data Structures 425', 'DATA2220');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linear Algebra Lab', 'LINE5226');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Marketing Management', 'MARK7666');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Music Theory Workshop', 'MUSI8922');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Law 236', 'BUSI2456');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Cryptography', 'CRYP3760');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Statistics', 'STAT4786');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Differential Equations 434', 'DIFF7275');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Astrophysics', 'ASTR6901');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organizational Behavior 436', 'ORGA4281');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anthropology IV', 'ANTH5514');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Art History I', 'ARTH8067');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Data Structures IV', 'DATA6080');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anatomy I', 'ANAT8739');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Earth Science', 'EART7273');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Kinesiology Workshop', 'KINE3635');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Bioethics', 'BIOE3300');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Medical Imaging 268', 'MEDI3543');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cryptography Lab', 'CRYP1528');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Pathology', 'PATH8808');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Information Systems', 'INFO7272');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pathology 499', 'PATH7295');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Artificial Intelligence', 'ARTI5495');
INSERT IGNORE INTO courses (name, course_code) VALUES ('World History Lab', 'WORL1011');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance Workshop', 'CORP9474');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Corporate Finance', 'CORP4944');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on Computer Networks', 'COMP8522');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Entrepreneurship', 'ENTR7649');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Bioethics', 'BIOE1811');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Modern Organic Chemistry', 'ORGA6361');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology Lab', 'TOXI3895');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Cloud Computing', 'CLOU9666');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Genetics', 'GENE2310');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Business Ethics', 'BUSI9930');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Microeconomics IV', 'MICR3372');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Modern Database Systems', 'DATA4532');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Information Systems 209', 'INFO2394');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Nursing Practice', 'NURS9098');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Macroeconomics 373', 'MACR6150');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Sports Medicine 511', 'SPOR2457');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Supply Chain Management I', 'SUPP5163');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Occupational Therapy 381', 'OCCU8176');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Political Science 300', 'POLI9198');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Software Engineering', 'SOFT2760');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Computer Networks', 'COMP6128');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of Cybersecurity', 'CYBE7628');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Computer Science', 'COMP7204');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Calculus IV', 'CALC9534');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Biomechanics', 'BIOM3371');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Discrete Mathematics 376', 'DISC2568');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Algorithm Analysis IV', 'ALGO2815');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Medical Imaging I', 'MEDI5814');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Operating Systems', 'OPER4164');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Database Systems Seminar', 'DATA4155');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of Health Informatics', 'HEAL7996');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Networks III', 'COMP8248');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Business Ethics', 'BUSI9680');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Differential Equations Independent Study', 'DIFF8029');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology II', 'PHYS3163');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Web Development IV', 'WEBD4547');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning 166', 'MACH9925');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Probability IV', 'PROB1372');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Oceanography 429', 'OCEA8200');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ethics 171', 'ETHI8868');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Web Development 563', 'WEBD4569');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on Web Development', 'WEBD4051');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Statistics 481', 'STAT2797');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Algorithm Analysis', 'ALGO6499');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Law 391', 'BUSI1038');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Health Informatics', 'HEAL9901');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Medical Imaging II', 'MEDI6723');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Robotics', 'ROBO5225');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Robotics Lab', 'ROBO9212');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pathology 599', 'PATH3807');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cryptography Seminar', 'CRYP9344');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anthropology 320', 'ANTH2507');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Bioethics Seminar', 'BIOE7954');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Environmental Science', 'ENVI4181');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Occupational Therapy Seminar', 'OCCU6486');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Macroeconomics Practicum', 'MACR8536');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Marketing Management 436', 'MARK3613');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Probability 270', 'PROB3732');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Financial Accounting', 'FINA9243');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Operating Systems 156', 'OPER7393');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Law 281', 'BUSI9001');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organizational Behavior 501', 'ORGA5258');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Neuroscience 453', 'NEUR4155');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Artificial Intelligence 391', 'ARTI9657');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology 199', 'PHYS7093');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organic Chemistry 380', 'ORGA5433');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Public Health 483', 'PUBL5071');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Creative Writing I', 'CREA7904');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Philosophy 572', 'PHIL5737');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Data Structures 558', 'DATA9741');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of Pharmacology', 'PHAR9444');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Quantum Mechanics', 'QUAN7914');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Immunology Independent Study', 'IMMU3954');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organizational Behavior 481', 'ORGA7777');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Occupational Therapy 181', 'OCCU7211');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of Nutrition', 'NUTR7256');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organizational Behavior Lab', 'ORGA7863');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Discrete Mathematics', 'DISC5825');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Macroeconomics', 'MACR1902');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ecology 378', 'ECOL6824');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Genetics III', 'GENE4650');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Kinesiology 229', 'KINE5713');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Software Engineering 240', 'SOFT6824');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Music Theory Lab', 'MUSI7391');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Genetics', 'GENE9225');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Artificial Intelligence 470', 'ARTI9886');
INSERT IGNORE INTO courses (name, course_code) VALUES ('World History 471', 'WORL5640');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Business Ethics', 'BUSI8493');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Entrepreneurship', 'ENTR8452');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Linear Algebra', 'LINE8244');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Oceanography', 'OCEA7678');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Marketing Management Workshop', 'MARK2725');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Philosophy 213', 'PHIL9628');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on Ethics', 'ETHI7733');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Bioethics', 'BIOE7015');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Occupational Therapy', 'OCCU5898');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pathology Seminar', 'PATH5141');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linguistics II', 'LING2365');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Creative Writing II', 'CREA5828');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance Independent Study', 'CORP8821');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology 382', 'TOXI6254');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Nutrition II', 'NUTR8508');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Human Resource Management', 'HUMA4977');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Cognitive Science', 'COGN8588');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Operating Systems 302', 'OPER7792');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ecology 316', 'ECOL4831');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations I', 'INTE4129');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Microeconomics III', 'MICR4317');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Information Systems 517', 'INFO7294');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on Bioethics', 'BIOE1593');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Oceanography 386', 'OCEA8712');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Statistics 326', 'STAT4290');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Science 334', 'COMP2854');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning IV', 'MACH8760');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Physiology', 'PHYS3125');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Political Science 239', 'POLI8914');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Modern Algorithm Analysis', 'ALGO5776');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Human-Computer Interaction', 'HUMA2146');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Literature 383', 'LITE6846');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Psychology', 'PSYC8255');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Applied Public Health', 'PUBL2470');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Medical Imaging', 'MEDI4424');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Biomechanics 412', 'BIOM8237');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning 241', 'MACH1530');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on Immunology', 'IMMU9271');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology 391', 'PHYS9318');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Creative Writing Lab', 'CREA4612');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Cybersecurity', 'CYBE8480');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Probability', 'PROB8153');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Pharmacology', 'PHAR1407');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Thermodynamics', 'THER3517');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Environmental Science I', 'ENVI1885');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Linguistics', 'LING5434');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Database Systems Independent Study', 'DATA1249');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Political Science', 'POLI7067');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ethics 527', 'ETHI4454');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Gerontology II', 'GERO7711');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organizational Behavior 409', 'ORGA4135');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Sports Medicine', 'SPOR2795');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Bioethics II', 'BIOE6007');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Earth Science', 'EART9604');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Probability Practicum', 'PROB3806');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Astrophysics', 'ASTR9504');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Machine Learning', 'MACH7164');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Database Systems 532', 'DATA4198');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology IV', 'EPID1629');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Earth Science Workshop', 'EART5067');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ethics 445', 'ETHI4824');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology Practicum', 'EPID1896');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Information Systems 589', 'INFO5395');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance IV', 'CORP3289');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Software Engineering 462', 'SOFT5393');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Supply Chain Management IV', 'SUPP6731');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Ecology', 'ECOL4309');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance II', 'CORP5118');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Statistics', 'STAT3146');
INSERT IGNORE INTO courses (name, course_code) VALUES ('European History 173', 'EURO2178');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Astrophysics 579', 'ASTR6954');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cloud Computing 208', 'CLOU8434');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Health Informatics', 'HEAL5560');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human Resource Management 560', 'HUMA6768');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Calculus 393', 'CALC2737');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology 124', 'EPID3761');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ethics Independent Study', 'ETHI5760');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Thermodynamics 389', 'THER8166');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cognitive Science 213', 'COGN2919');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology III', 'EPID7345');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Applied Artificial Intelligence', 'ARTI1957');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology 250', 'PHYS2214');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Quantum Mechanics', 'QUAN1946');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Modern Anthropology', 'ANTH4165');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Algorithm Analysis', 'ALGO6097');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Topics in Physiology', 'PHYS2279');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Oceanography 197', 'OCEA2471');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human Resource Management 240', 'HUMA5953');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Creative Writing Independent Study', 'CREA4345');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ecology Practicum', 'ECOL9294');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Entrepreneurship 469', 'ENTR4783');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pharmacology IV', 'PHAR3233');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Astrophysics', 'ASTR4728');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Machine Learning III', 'MACH4390');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Quantum Mechanics Workshop', 'QUAN6809');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Thermodynamics III', 'THER6045');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Law 234', 'BUSI7319');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linguistics 340', 'LING2520');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Organizational Behavior 525', 'ORGA5512');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Science II', 'COMP9211');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anthropology 197', 'ANTH2529');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Genetics 565', 'GENE6599');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations III', 'INTE6851');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Psychology II', 'PSYC4717');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Neuroscience II', 'NEUR7432');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anthropology Lab', 'ANTH8361');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Information Systems Independent Study', 'INFO3984');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Neuroscience', 'NEUR2662');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Occupational Therapy Workshop', 'OCCU8527');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anatomy 274', 'ANAT6013');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ethics 532', 'ETHI3459');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Organizational Behavior', 'ORGA6000');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations 184', 'INTE3385');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Science Independent Study', 'COMP2270');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Entrepreneurship Lab', 'ENTR1657');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology 503', 'TOXI8254');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Science Practicum', 'COMP5549');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Discrete Mathematics', 'DISC3884');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linguistics 191', 'LING5417');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Differential Equations Practicum', 'DIFF7281');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Robotics IV', 'ROBO5900');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Occupational Therapy', 'OCCU1153');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Ethics Workshop', 'BUSI8127');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Ethics IV', 'BUSI4123');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Ethics 135', 'BUSI4431');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on World History', 'WORL8835');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human-Computer Interaction 419', 'HUMA7150');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Database Systems 176', 'DATA1871');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Political Science 582', 'POLI9730');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Web Development 281', 'WEBD7252');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Physical Therapy', 'PHYS1627');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations Seminar', 'INTE2595');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Science I', 'COMP6690');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Discrete Mathematics 255', 'DISC9417');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Business Law', 'BUSI2266');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Macroeconomics', 'MACR3528');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Software Engineering 243', 'SOFT4471');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Pathology', 'PATH7981');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Astrophysics', 'ASTR1057');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Applied Calculus', 'CALC3340');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Political Science 308', 'POLI8429');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Astrophysics I', 'ASTR9403');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of Creative Writing', 'CREA1242');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Toxicology', 'TOXI5641');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Robotics 115', 'ROBO6351');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Differential Equations 480', 'DIFF6915');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Literature II', 'LITE3129');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Occupational Therapy IV', 'OCCU6445');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Neuroscience III', 'NEUR8594');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology 380', 'PHYS8552');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Anthropology Seminar', 'ANTH7629');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Anatomy', 'ANAT6336');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations 368', 'INTE2530');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology 413', 'EPID6660');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Database Systems 333', 'DATA4442');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of Artificial Intelligence', 'ARTI9244');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Corporate Finance 375', 'CORP3603');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Applied Epidemiology', 'EPID2228');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cryptography 124', 'CRYP7941');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linear Algebra II', 'LINE4919');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Cloud Computing', 'CLOU3774');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in European History', 'EURO8000');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Sports Medicine', 'SPOR3863');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Cognitive Science', 'COGN3527');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Information Systems 439', 'INFO5425');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Pathology', 'PATH2191');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Web Development 296', 'WEBD9018');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Biomechanics 571', 'BIOM7099');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Art History 291', 'ARTH2483');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology 473', 'EPID9011');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of European History', 'EURO1665');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Thermodynamics 211', 'THER5306');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Political Science II', 'POLI3732');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on Nursing Practice', 'NURS1504');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Genetics 284', 'GENE3789');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Modern World History', 'WORL1194');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Oceanography Independent Study', 'OCEA7206');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Organic Chemistry', 'ORGA3719');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Gerontology 337', 'GERO3198');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Microeconomics 123', 'MICR3346');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Data Structures', 'DATA3571');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Advanced Immunology', 'IMMU5614');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Genetics 109', 'GENE8566');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Experimental Molecular Biology', 'MOLE2570');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cryptography II', 'CRYP8252');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations Lab', 'INTE5971');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Statistics Lab', 'STAT5239');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linear Algebra IV', 'LINE6321');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Operating Systems IV', 'OPER2230');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Neuroscience 512', 'NEUR3076');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human Resource Management Lab', 'HUMA5323');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Information Systems', 'INFO8626');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Literature Workshop', 'LITE1607');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Sociology II', 'SOCI6405');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Quantum Mechanics 353', 'QUAN3699');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Immunology 190', 'IMMU7864');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Differential Equations III', 'DIFF8422');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Financial Accounting Independent Study', 'FINA9138');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Computer Science 439', 'COMP5872');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Pharmacology', 'PHAR9912');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Calculus 215', 'CALC5734');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Applied Pharmacology', 'PHAR6326');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Toxicology IV', 'TOXI9124');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Business Law', 'BUSI5411');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Modern Oceanography', 'OCEA5117');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Physiology 432', 'PHYS6472');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of European History', 'EURO7067');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Linguistics Independent Study', 'LING5749');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Business Law Practicum', 'BUSI9202');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Public Health', 'PUBL6662');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Sociology', 'SOCI5586');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Psychology Independent Study', 'PSYC7982');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pathology 447', 'PATH9473');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human Resource Management 429', 'HUMA9418');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Software Engineering IV', 'SOFT5567');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Probability', 'PROB7258');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology 429', 'EPID7313');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Occupational Therapy 576', 'OCCU4889');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Perspectives on Physiology', 'PHYS2920');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Foundations of Algorithm Analysis', 'ALGO7617');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Human Resource Management Independent Study', 'HUMA3118');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Statistics', 'STAT9864');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Literature 463', 'LITE2181');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Discrete Mathematics III', 'DISC9898');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Sociology', 'SOCI2980');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Entrepreneurship 508', 'ENTR5043');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations 279', 'INTE6192');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cryptography I', 'CRYP3048');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Philosophy Independent Study', 'PHIL5891');
INSERT IGNORE INTO courses (name, course_code) VALUES ('International Relations 572', 'INTE7905');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Seminar in Linguistics', 'LING2346');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Research Methods in Robotics', 'ROBO2570');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Bioethics 504', 'BIOE2433');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Business Ethics', 'BUSI3068');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Molecular Biology Workshop', 'MOLE6319');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Sports Medicine IV', 'SPOR2406');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Neuroscience Seminar', 'NEUR7501');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Quantum Mechanics 509', 'QUAN9512');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology 352', 'EPID1300');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Biomechanics 574', 'BIOM3929');
INSERT IGNORE INTO courses (name, course_code) VALUES ('World History 557', 'WORL1478');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Fundamentals of Quantum Mechanics', 'QUAN9026');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Political Science', 'POLI8826');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Music Theory 127', 'MUSI3738');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Web Development', 'WEBD9799');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Cybersecurity Lab', 'CYBE4776');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Public Health', 'PUBL9655');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Survey of Biomechanics', 'BIOM9963');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Nursing Practice IV', 'NURS6380');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Molecular Biology', 'MOLE4464');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Genetics', 'GENE3175');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Sports Medicine Practicum', 'SPOR1887');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Theoretical Art History', 'ARTH8689');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Entrepreneurship Independent Study', 'ENTR3284');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Microeconomics 478', 'MICR9210');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pharmacology Seminar', 'PHAR9293');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Psychology 481', 'PSYC5566');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Ethics III', 'ETHI6787');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Pharmacology 591', 'PHAR6176');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology Independent Study', 'EPID6688');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Contemporary Operating Systems', 'OPER3640');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Bioethics III', 'BIOE3803');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Molecular Biology 259', 'MOLE9499');
INSERT IGNORE INTO courses (name, course_code) VALUES ('European History 128', 'EURO3963');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Epidemiology I', 'EPID9182');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Gerontology', 'GERO8307');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Occupational Therapy', 'OCCU9784');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Introduction to Creative Writing', 'CREA6077');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Principles of Robotics', 'ROBO4224');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Issues in Medical Imaging', 'MEDI4266');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Data Structures 354', 'DATA3857');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Quantum Mechanics Independent Study', 'QUAN7839');
INSERT IGNORE INTO courses (name, course_code) VALUES ('Web Development 174', 'WEBD1410');

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
SET AUTOCOMMIT = 1;
